=== jingjingliao/CS5200/CS5200.PracticumII.LiaoJ-ZhangM/pubmed-tfm-xml/articles.dtd
<!ELEMENT PubmedArticleSet (PubmedArticle*)>
  
  <!ELEMENT PubmedArticle (Article)>
  <!ATTLIST PubmedArticle PMID CDATA #REQUIRED>
  <!ELEMENT Article (Journal*, Language*, ArticleTitle*, AuthorList*)>

  <!ELEMENT Journal (ISSN*, JournalIssue*, Title*, ISOAbbreviation*)>
  <!ATTLIST ISSN IssnType CDATA #REQUIRED>
  <!ELEMENT JournalIssue (Volume*, Issue*, PubDate*)>
  <!ATTLIST JournalIssue CitedMedium CDATA #REQUIRED>
  <!ELEMENT PubDate (Year*, Month*, Day*)>

  <!ELEMENT AuthorList (Author*)>
  <!ATTLIST AuthorList CompleteYN CDATA #REQUIRED>
  <!ELEMENT Author (LastName*, ForeName*, Initials*)>
  <!ATTLIST Author ValidYN CDATA #REQUIRED>

  <!ELEMENT Language (#PCDATA)>
  <!ELEMENT ArticleTitle (#PCDATA)>

  <!ELEMENT Year (#PCDATA)>
  <!ELEMENT Month (#PCDATA)>
  <!ELEMENT Day (#PCDATA)>
  <!ELEMENT Issue (#PCDATA)>
  <!ELEMENT Volume (#PCDATA)>
  <!ELEMENT ISSN (#PCDATA)>
  <!ELEMENT Title (#PCDATA)>
  <!ELEMENT ISOAbbreviation (#PCDATA)>

  <!ELEMENT LastName (#PCDATA)>
  <!ELEMENT ForeName (#PCDATA)>
  <!ELEMENT Initials (#PCDATA)>

=== jingjingliao/CS5200/CS5200.PracticumII.LiaoJ-ZhangM/pubmed-tfm-xml/sampleData.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE PubmedArticleSet SYSTEM "articles.dtd">

<PubmedArticleSet>
	<PubmedArticle PMID="1">
		<Article>
			<Journal>
				<ISSN IssnType="Print">0006-2944</ISSN>
				<JournalIssue CitedMedium="Print">
					<Volume>13</Volume>
					<Issue>2</Issue>
					<PubDate>
						<Year>1975</Year>
						<Month>Jun</Month>
					</PubDate>
				</JournalIssue>
				<Title>Biochemical medicine</Title>
				<ISOAbbreviation>Biochem Med</ISOAbbreviation>
			</Journal>
			<Language>eng</Language>
			<ArticleTitle>Formate assay in body fluids: application in methanol poisoning.</ArticleTitle>
			<AuthorList CompleteYN="Y">
				<Author ValidYN="Y">
					<LastName>Makar</LastName>
					<ForeName>A B</ForeName>
					<Initials>AB</Initials>
				</Author>
				<Author ValidYN="Y">
					<LastName>McMartin</LastName>
					<ForeName>K E</ForeName>
					<Initials>KE</Initials>
				</Author>
				<Author ValidYN="Y">
					<LastName>Palese</LastName>
					<ForeName>M</ForeName>
					<Initials>M</Initials>
				</Author>
				<Author ValidYN="Y">
					<LastName>Tephly</LastName>
					<ForeName>T R</ForeName>
					<Initials>TR</Initials>
				</Author>
			</AuthorList>
		</Article>
	</PubmedArticle>
	<PubmedArticle PMID="1">
		<Article>
			<Journal>
				<ISSN IssnType="Print">0006-2944</ISSN>
				<JournalIssue CitedMedium="Print">
					<Volume>13</Volume>
					<Issue>2</Issue>
					<PubDate>
						<Year>1975</Year>
						<Month>Jun</Month>
						
					</PubDate>
				</JournalIssue>
				<Title>Biochemical medicine</Title>
				<ISOAbbreviation>Biochem Med</ISOAbbreviation>
			</Journal>
			<Language>eng</Language>
			<ArticleTitle>Formate assay in body fluids: application in methanol poisoning.</ArticleTitle>
			<AuthorList CompleteYN="Y">
				<Author ValidYN="Y">
					<LastName>Makar</LastName>
					<ForeName>A B</ForeName>
					<Initials>AB</Initials>
				</Author>
				<Author ValidYN="Y">
					<LastName>McMartin</LastName>
					<ForeName>K E</ForeName>
					<Initials>KE</Initials>
				</Author>
				<Author ValidYN="Y">
					<LastName>Palese</LastName>
					<ForeName>M</ForeName>
					<Initials>M</Initials>
				</Author>
				<Author ValidYN="Y">
					<LastName>Tephly</LastName>
					<ForeName>T R</ForeName>
					<Initials>TR</Initials>
				</Author>
			</AuthorList>
		</Article>
	</PubmedArticle>
	<PubmedArticle PMID="13700">
		<Article>
		  <Journal>
			<ISSN IssnType="Print">0003-4509</ISSN>
			<JournalIssue CitedMedium="Print">
			  <Volume>34</Volume>
			  <Issue>9-10</Issue>
			  <PubDate>
				<MedlineDate>1976 Sep-Oct</MedlineDate>
			  </PubDate>
			</JournalIssue>
			<Title>Annales pharmaceutiques francaises</Title>
			<ISOAbbreviation>Ann Pharm Fr</ISOAbbreviation>
		  </Journal>
		  <Language>fre</Language>
		  <ArticleTitle>[Influence of acute and chronic alcoholism on the activity of two benzodiazepines: oxazepam and medazepam].</ArticleTitle>
		  <AuthorList CompleteYN="Y">
			<Author ValidYN="Y">
			  <LastName>Bourrinet</LastName>
			  <ForeName>P</ForeName>
			  <Initials>P</Initials>
			</Author>
			<Author ValidYN="Y">
			  <LastName>Takeda</LastName>
			  <ForeName>H</ForeName>
			  <Initials>H</Initials>
			</Author>
		  </AuthorList>
		</Article>
	  </PubmedArticle>
	<PubmedArticle PMID="13897">
	<Article>
		<Journal>
		<ISSN IssnType="Print">0007-5140</ISSN>
		<JournalIssue CitedMedium="Print">
			<Volume>50</Volume>
			<Issue>4</Issue>
			<PubDate>
			<Year>1976</Year>
			<Season>Winter</Season>
			</PubDate>
		</JournalIssue>
		<Title>Bulletin of the history of medicine</Title>
		<ISOAbbreviation>Bull Hist Med</ISOAbbreviation>
		</Journal>
		<Language>eng</Language>
		<ArticleTitle>Ren√© Dubos and the capsular polysaccharide of pneumococcus: an oral history memoir.</ArticleTitle>
		<AuthorList CompleteYN="Y">
		<Author ValidYN="Y">
			<LastName>Benison</LastName>
			<ForeName>S</ForeName>
			<Initials>S</Initials>
		</Author>
		</AuthorList>
	</Article>
	</PubmedArticle>
	<PubmedArticle PMID="13916">
		<Article>
		  <Journal>
			<ISSN IssnType="Print">0008-4018</ISSN>
			<JournalIssue CitedMedium="Print">
			  <Volume>55</Volume>
			  <Issue>1</Issue>
			  <PubDate>
				<Year>1977</Year>
				<Month>Jan</Month>
			  </PubDate>
			</JournalIssue>
			<Title>Canadian journal of biochemistry</Title>
			<ISOAbbreviation>Can J Biochem</ISOAbbreviation>
		  </Journal>
		  <Language>eng</Language>
		  <ArticleTitle>Characterization and substrate specificity of fumarylacetoacetate fumarylhydrolase.</ArticleTitle>
		  <AuthorList CompleteYN="Y">
			<Author ValidYN="Y">
			  <LastName>Mahuran</LastName>
			  <ForeName>D J</ForeName>
			  <Initials>DJ</Initials>
			</Author>
			<Author ValidYN="Y">
			  <LastName>Angus</LastName>
			  <ForeName>R H</ForeName>
			  <Initials>RH</Initials>
			</Author>
			<Author ValidYN="Y">
			  <LastName>Braun</LastName>
			  <ForeName>C V</ForeName>
			  <Initials>CV</Initials>
			</Author>
			<Author ValidYN="Y">
			  <LastName>Sim</LastName>
			  <ForeName>S S</ForeName>
			  <Initials>SS</Initials>
			</Author>
			<Author ValidYN="Y">
			  <LastName>Schmidt</LastName>
			  <ForeName>D E</ForeName>
			  <Initials>DE</Initials>
			  <Suffix>Jr</Suffix>
			</Author>
		  </AuthorList>
		</Article>
	  </PubmedArticle>
	  <PubmedArticle PMID="17090">
		<Article>
		  <Journal>
			<ISSN IssnType="Print">0304-3959</ISSN>
			<JournalIssue CitedMedium="Print">
			  <Volume>2</Volume>
			  <Issue>3</Issue>
			  <PubDate>
				<Year>1976</Year>
				<Month>Sep</Month>
			  </PubDate>
			</JournalIssue>
			<Title>Pain</Title>
			<ISOAbbreviation>Pain</ISOAbbreviation>
		  </Journal>
		  <Language>eng</Language>
		  <ArticleTitle>A comprehensive treatment approach to chronic low back pain.</ArticleTitle>
		  <AuthorList CompleteYN="Y">
			<Author ValidYN="Y">
			  <LastName>Cairns</LastName>
			  <ForeName>Douglas</ForeName>
			  <Initials>D</Initials>
			  <AffiliationInfo>
				<Affiliation>Spine Center, Rancho Los Amigos Hospital, 7601 East Imperial Highway, Downey, Calif. 90242 U.S.A.</Affiliation>
			  </AffiliationInfo>
			</Author>
			<Author ValidYN="Y">
			  <LastName>Thomas</LastName>
			  <ForeName>Lynn</ForeName>
			  <Initials>L</Initials>
			</Author>
			<Author ValidYN="Y">
			  <LastName>Mooney</LastName>
			  <ForeName>Vert</ForeName>
			  <Initials>V</Initials>
			</Author>
			<Author ValidYN="Y">
			  <LastName>Pace</LastName>
			  <ForeName>Blair J</ForeName>
			  <Initials>BJ</Initials>
			</Author>
		  </AuthorList>
		</Article>
	  </PubmedArticle>
	  <PubmedArticle PMID="13696">
		<Article>
		  <Journal>
			<ISSN IssnType="Electronic">1539-3704</ISSN>
			<JournalIssue CitedMedium="Internet">
			  <Volume>86</Volume>
			  <Issue>2</Issue>
			  <PubDate>
				<Year>1977</Year>
				<Month>Feb</Month>
			  </PubDate>
			</JournalIssue>
			<Title>Annals of internal medicine</Title>
			<ISOAbbreviation>Ann Intern Med</ISOAbbreviation>
		  </Journal>
		  <Language>eng</Language>
		  <ArticleTitle>Bone marrow transplantation with intensive combination chemotherapy/radiation therapy (SCARI) in acute leukemia.</ArticleTitle>
		  <AuthorList CompleteYN="Y">
			<Author ValidYN="Y">
			  <CollectiveName>The UCLA Bone Marrow Transplantation Group</CollectiveName>
			</Author>
		  </AuthorList>
		</Article>
	  </PubmedArticle>
	  <PubmedArticle PMID="196">
		<Article>
		  <Journal>
			<ISSN IssnType="Electronic">1539-3704</ISSN>
			<JournalIssue CitedMedium="Internet">
			  <Volume>86</Volume>
			  <Issue>2</Issue>
			  <PubDate>
				<Year>1977</Year>
				<Month>Feb</Month>
			  </PubDate>
			</JournalIssue>
			<Title>Annals of internal medicine</Title>
			<ISOAbbreviation>Ann Intern Med</ISOAbbreviation>
		  </Journal>
		  <Language>eng</Language>
		  <ArticleTitle>Bone marrow transplantation with intensive combination chemotherapy/radiation therapy (SCARI) in acute leukemia.</ArticleTitle>
		  <AuthorList CompleteYN="Y">
		  </AuthorList>
		</Article>
	  </PubmedArticle>
	  <PubmedArticle PMID="152">
		<Article>
		  <Journal>
			<JournalIssue CitedMedium="Print">
			  <Volume>280</Volume>
			  <Issue>13</Issue>
			  <PubDate>
				<Year>1975</Year>
				<Month>Apr</Month>
				<Day>07</Day>
			  </PubDate>
			</JournalIssue>
			<Title>Comptes rendus hebdomadaires des seances de l'Academie des sciences. Serie D: Sciences naturelles</Title>
			<ISOAbbreviation>C R Acad Hebd Seances Acad Sci D</ISOAbbreviation>
		  </Journal>
		  <Language>fre</Language>
		  <ArticleTitle>[Spontaneous mortality and vascular lesions in 3 rat strains with different blood pressure levels].</ArticleTitle>
		  <AuthorList CompleteYN="Y">
			<Author ValidYN="Y">
			  <LastName>Dupont</LastName>
			  <ForeName>J</ForeName>
			  <Initials>J</Initials>
			</Author>
			<Author ValidYN="Y">
			  <LastName>Dupont</LastName>
			  <ForeName>J C</ForeName>
			  <Initials>JC</Initials>
			</Author>
			<Author ValidYN="Y">
			  <LastName>Milon</LastName>
			  <ForeName>H</ForeName>
			  <Initials>H</Initials>
			</Author>
			<Author ValidYN="Y">
			  <LastName>Froment</LastName>
			  <ForeName>A</ForeName>
			  <Initials>A</Initials>
			</Author>
		  </AuthorList>
		</Article>
	  </PubmedArticle>
	  <PubmedArticle PMID="168">
		<Article>
		  <Journal>
			<ISSN IssnType="Print">0009-921X</ISSN>
			<JournalIssue CitedMedium="Print">
			  <Issue>113</Issue>
			  <PubDate>
				<MedlineDate>1975 Nov-Dec</MedlineDate>
			  </PubDate>
			</JournalIssue>
			<Title>Clinical orthopaedics and related research</Title>
			<ISOAbbreviation>Clin Orthop Relat Res</ISOAbbreviation>
		  </Journal>
		  <Language>eng</Language>
		  <ArticleTitle>Effects of graded infusions of monomethylmethacrylate on coagulation, blood lipids, respiration and circulation. An experimental study in dogs.</ArticleTitle>
		  <AuthorList CompleteYN="Y">
			<Author ValidYN="Y">
			  <LastName>Modig</LastName>
			  <ForeName>J</ForeName>
			  <Initials>J</Initials>
			</Author>
			<Author ValidYN="Y">
			  <LastName>Busch</LastName>
